from pydantic import BaseModel


order_fields = {
            "客户名称": "string",
            "发车联系人": "string",
            "发车联系人手机号": "string (11位数字)",
            "始发地": "省+市+区+详细地址",
            "收车联系人": "string",
            "收车联系人手机号": "string (11位数字)",
            "目的地": "省+市+区+详细地址",
            "装车时间": "datetime (yyyy-MM-dd)",
            "发车时间": "datetime (yyyy-MM-dd)",
            "订单总金额": "float (万元)",
            "汽车品牌": "string",
            "车辆系列": "string",
            "车值": "float (万元)",
            "车辆数量": "integer",
            "VIN码": "string (多个用英文逗号分隔)",
            "承运类型": "enum (1: 平台自营, 2: 三方竞价)",
            "购买保险": "boolean",
            "保险类型": "enum (尊享服务/全程无忧)",
            "车辆类型": "enum (0: 新车, 1: 二手车)",
            "车辆产地": "enum (0: 国产, 1: 进口)",
            "板车要求": "string",
            "验车要求": "string",
            "备注说明": "string",
            "时效类型": "integer",
            "运力方式": "enum (1: 派单, 2: 抢单)",
            "车辆性质": "enum (OrderDetailEnums.CarNature)",
            "订单金额是否含税": "enum (10: 含税, 20: 不含税, 30: 待确认)",
            "vinList": "array<string>",
            "预约单id": "integer",
            "订单税率": "float (百分比%)",
            "收车省": "string",
            "收车市": "string",
            "收车区": "string",
            "预约单号": "string",
            "运输类型": "enum (3: 自有运输, 4: 委托待运)",
            "是否生成运单": "boolean",
            "收车地址经纬度": "object { lat: float, lng: float }",
            "发车省": "string",
            "发车市": "string",
            "发车区": "string",
            "是否需要发票": "enum (0: 不需要, 1: 需要)",
            "订单税前金额": "float (万元)",
            "发车地址经纬度": "object { lat: float, lng: float }",
            "订单车辆明细信息": "array<OrderDetailDto>",
            "大客户订单号": "string",
            "微信客户ID": "string",
            "客户类型": "enum (0: 个人, 1: 企业)",
            "客户ID": "integer",
            "租户ID": "integer",
            "线路ID": "integer",
            "是否支付": "enum (1: 已支付, 0: 未支付)",
            "是否转单": "boolean",
            "订单来源": "enum (1: API, 2: 管理端, 3: 客户端)",
            "收款截图": "string",
            "创建人手机号": "string",
            "经销商用户ID": "integer",
            "是否取消验车": "enum (10: 否, 20: 是)",
            "支付失效时间": "datetime (ISO 8601)",
            "付款类型": "enum (10: 全款, 20: 定金)",
            "已付款金额": "float (万元)",
            "是否需要回单": "enum (10: 不需要, 20: 线上回单, 30: 纸质回单)",
            "创建人ID": "integer",
            "提送规则": "enum (OrderEnums.OrderSubmitType)",
            "询价单ID": "integer",
            "询价报价ID": "integer",
            "询价信息": "object (Enquiry)",
            "报价信息": "object (EnquiryQuotation)",
            "创建时间": "datetime (ISO 8601)",
            "更新时间": "datetime (ISO 8601)",
            "邀请码": "string",
            "渠道ID": "integer"
}

class ExtractionResult(BaseModel):
    content_type: str  # image/audio/text
    original_data: str
    extracted_fields: dict
    confidence: float
