from pydantic import BaseModel


order_fields = {
  "customerName": "string (客户名称 必填)",
  "senderName": "string (发车联系人 必填)",
  "senderPhone": "string (发车联系电话 必填)",
  "senderAddress": "string (发车地址 必填)",
  "receiverName": "string (收车联系人 必填)",
  "receiverPhone": "string (收车联系电话 必填)",
  "receiverAddress": "string (收车地址 必填)",
  "pickupTime": "string (ISO 8601 datetime) (预计装车时间 必填)",
  "expectDepartureTime": "string (ISO 8601 datetime) (预计发车时间)",
  "afterAmount": "number (BigDecimal) (订单税后金额(含税) 必填)",
  "brand": "string (汽车品牌)",
  "vehicleName": "string (车辆系列)",
  "price": "string (车值(万元)  必填)",
  "vehicleCount": "integer (车辆数量  必填)",
  "vins": "string (VIN码  必填)",
  "carrierType": "integer (Byte) (承运信息. 1: 平台自营. 2: 三方竞价)",
  "insuranceRequired": "boolean (是否购买保险)",
  "insuranceType": "object (OrderEnums.InsuranceType) (保险类型)",
  "carType": "object (OrderDetailEnums.CarType) (车辆类型. 0: 新车. 1: 二手车)",
  "carOrigin": "integer (Byte) (车辆产地. 0: 国产车. 1: 进口车)",
  "verifyRequire": "string (验车要求)",
  "trolleyRequire": "string (板车要求)",
  "remark": "string (备注说明)",
  "ageingType": "integer (时效类型)",
  "capacityType": "integer (运力方式, 1:派单 2:抢单)",
  "carNature": "object (OrderDetailEnums.CarNature) (车辆性质)",
  "includedTaxType": "integer (是否含税 10=含税 20=不含税 30=待确认)",
  "vinList": "array (List<String>)",
  "reservationId": "integer (Long) (预约单id)",
  "tax": "number (Double) (订单税率. 单位%)",
  "receiverDistrict": "string (收车区)",
  "receiverProvince": "string (收车省)",
  "receiverCity": "string (收车市)",
  "reservationNumber": "string (预约单号)",
  "transportationType": "integer (运输类型：3：自有运输，4：委托待运)",
  "generateWaybill": "boolean",
  "receiverLatitude": "number (Double) (收车地址纬度)",
  "receiverLongitude": "number (Double) (收车地址经度)",
  "senderProvince": "string (发车省)",
  "senderCity": "string (发车市)",
  "senderDistrict": "string (发车区)",
  "needTax": "integer (Byte) (是否需要发票(0: 不需要. 1: 需要))",
  "beforeAmount": "number (BigDecimal) (订单税前金额(不含税))",
  "senderLatitude": "number (Double) (发车地址纬度)",
  "senderLongitude": "number (Double) (发车地址经度)",
  "orderDetails": "array (List<OrderDetailDto>) (订单车辆明细信息)",
  "externalOrderNumber": "string (大客户的订单号)",
  "wechatCustomerId": "string (微信下单客户)",
  "customerType": "integer (Byte) (客户类型. 1: 企业用户. 0: 个人用户)",
  "customerId": "integer (Long) (客户id)",
  "tenantId": "integer (Long)",
  "line": "integer",
  "hasPayed": "integer (Byte) (是否已经支付. 1: 已支付. 0: 未支付)",
  "isTransfer": "boolean",
  "source": "object (OrderEnums.OrderSource) (订单来源. API(1, \"api接口下单\"), MANAGER(2, \"管理端页面下单\"), CUSTOMER(3, \"c端客户下单\"))",
  "imagePath": "string (收款截图)",
  "createUserPhone": "string (创建人手机号 仅经销商)",
  "dealerUserId": "integer (Long) (经销商端下单人对应端saas用户ID)",
  "canalVerify": "integer (车辆无异常是否取消验车确认环节 10=否 20=是)",
  "payTimeExpire": "string (ISO 8601 datetime) (订单支付失效时间)",
  "payType": "integer (付款类型 10=全款付 20=定金付)",
  "payAmount": "number (BigDecimal) (已付款金额)",
  "needReceipt": "integer (是否需要回单 10-不需要回单 20-需要线上回单 30-需要纸质回单)",
  "createUser": "integer (Long)",
  "submitType": "object (OrderEnums.OrderSubmitType) (提送规则)",
  "enquiryId": "integer (Long) (询价单ID)",
  "enquiryQuotationId": "integer (Long) (询价单-报价单ID)",
  "enquiry": "object (Enquiry)",
  "enquiryQuotation": "object (EnquiryQuotation)",
  "createTime": "string (ISO 8601 datetime)",
  "updateTime": "string (ISO 8601 datetime)",
  "invitationCode": "string (邀请码)",
  "channelId": "integer (Long) (渠道ID)",
  "text": "string (文本内容)"
}


class ExtractionResult(BaseModel):
    content_type: str  # image/audio/text
    original_data: str
    extracted_fields: dict
    confidence: float
